/** Runs against a seeded local/CI server without creating any user or changing published content. */
import assert from 'node:assert/strict'
const base=process.env.CMS_TEST_URL||'http://localhost:3001'
const first=await fetch(`${base}/api/site-content`,{headers:{Origin:'http://localhost:3000'}})
assert.equal(first.status,200)
assert.match(first.headers.get('access-control-expose-headers')||'',/etag/i)
const snapshot=await first.json()
assert.ok(snapshot.pillars.length>=4,'seeded pillars appear')
assert.ok(Object.keys(snapshot.copy).length>0,'copy slots appear')
assert.ok(snapshot.pavilion.models?.heal,'3D model settings appear')
assert.ok(Array.isArray(snapshot.site.navigation)&&Array.isArray(snapshot.site.footerColumns)&&Array.isArray(snapshot.site.social),'menu, footer and social settings appear as lists')
assert.ok(snapshot.activities.some((activity:any)=>activity.hoverPhotos?.length&&activity.icon),'programme presentation fields appear')
assert.ok(snapshot.activities.every((activity:any)=>activity.record===undefined),'retired imported-data copies never reach the website')
const graphql=await fetch(`${base}/api/graphql`,{method:'POST'})
assert.equal(graphql.status,404,'GraphQL stays disabled')
const etag=first.headers.get('etag');assert.ok(etag)
const again=await fetch(`${base}/api/site-content`,{headers:{'If-None-Match':etag!}})
assert.equal(again.status,304)
const preview=await fetch(`${base}/api/site-content?preview=true`)
assert.equal(preview.status,401)
const directDraft=await fetch(`${base}/api/content-slots?draft=true&where[_status][equals]=draft`)
assert.equal(directDraft.status,200);assert.equal((await directDraft.json()).totalDocs,0)
const write=await fetch(`${base}/api/live-stats`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({key:'unauthorized-probe',label:'Unauthorized',value:'0',_status:'published'})})
assert.ok([401,403].includes(write.status),'anonymous statistics write is denied')
const statsAdmin=await fetch(`${base}/api/live-stats?limit=1`)
assert.ok(Array.isArray((await statsAdmin.json()).docs),'Payload statistics listing remains available to its admin')
const statsFeed=await fetch(`${base}/api/live-stats-feed`)
assert.ok((await statsFeed.json()).stats,'compact statistics feed remains separate from CRUD routes')
const preflight=await fetch(`${base}/api/site-content`,{method:'OPTIONS',headers:{Origin:'http://localhost:3000','Access-Control-Request-Method':'GET','Access-Control-Request-Headers':'if-none-match'}})
assert.match(preflight.headers.get('access-control-allow-headers')||'',/if-none-match/i)
console.log('CMS API smoke passed: seeded content and settings, ETag 304, CORS, draft privacy, GraphQL off, and anonymous write protection.')
