/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    pillars: Pillar;
    activities: Activity;
    events: Event;
    partners: Partner;
    awards: Award;
    'content-slots': ContentSlot;
    'asset-slots': AssetSlot;
    'gallery-items': GalleryItem;
    pages: Page;
    'component-settings': ComponentSetting;
    media: Media;
    'live-stats': LiveStat;
    'stat-audit': StatAudit;
    users: User;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    pillars: PillarsSelect<false> | PillarsSelect<true>;
    activities: ActivitiesSelect<false> | ActivitiesSelect<true>;
    events: EventsSelect<false> | EventsSelect<true>;
    partners: PartnersSelect<false> | PartnersSelect<true>;
    awards: AwardsSelect<false> | AwardsSelect<true>;
    'content-slots': ContentSlotsSelect<false> | ContentSlotsSelect<true>;
    'asset-slots': AssetSlotsSelect<false> | AssetSlotsSelect<true>;
    'gallery-items': GalleryItemsSelect<false> | GalleryItemsSelect<true>;
    pages: PagesSelect<false> | PagesSelect<true>;
    'component-settings': ComponentSettingsSelect<false> | ComponentSettingsSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    'live-stats': LiveStatsSelect<false> | LiveStatsSelect<true>;
    'stat-audit': StatAuditSelect<false> | StatAuditSelect<true>;
    users: UsersSelect<false> | UsersSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: null;
  globals: {
    'site-settings': SiteSetting;
    'pavilion-settings': PavilionSetting;
  };
  globalsSelect: {
    'site-settings': SiteSettingsSelect<false> | SiteSettingsSelect<true>;
    'pavilion-settings': PavilionSettingsSelect<false> | PavilionSettingsSelect<true>;
  };
  locale: null;
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * Heal, Enrich, Empower and Projects: the words, colours and summary figures used across the site.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pillars".
 */
export interface Pillar {
  id: number;
  /**
   * How the website finds this item. Set once; only an administrator can change it.
   */
  key: string;
  /**
   * Lower numbers come first.
   */
  order?: number | null;
  label: string;
  headline: string;
  body?: string | null;
  shortTagline?: string | null;
  subText?: string | null;
  /**
   * Script line under the photo emblem, e.g. “Care, in every leaf.”
   */
  emblemCaption?: string | null;
  cardImageAlt?: string | null;
  stats?:
    | {
        label: string;
        /**
         * Exactly as reported, e.g. 1,500,230.
         */
        value: string;
        id?: string | null;
      }[]
    | null;
  keyHighlights?:
    | {
        text: string;
        id?: string | null;
      }[]
    | null;
  /**
   * Hex colour such as #24785b. Pick it with the swatch.
   */
  accentA?: string | null;
  /**
   * Hex colour such as #24785b. Pick it with the swatch.
   */
  accentB?: string | null;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * Every programme and project: its reported figures, and how it looks on the website.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "activities".
 */
export interface Activity {
  id: number;
  /**
   * How the website finds this item. Set once; only an administrator can change it.
   */
  key: string;
  /**
   * Lower numbers come first.
   */
  order?: number | null;
  pillarId: 'heal' | 'enrich' | 'empower' | 'projects';
  title: string;
  period: string;
  blurb?: string | null;
  headline: {
    label: string;
    /**
     * Exactly as reported, e.g. 1,500,230.
     */
    value: string;
    id?: string | null;
  };
  dataPoints?:
    | {
        label: string;
        /**
         * Exactly as reported, e.g. 1,500,230.
         */
        value: string;
        id?: string | null;
      }[]
    | null;
  /**
   * Shown on the home page tile.
   */
  icon?:
    | (
        | 'droplets'
        | 'droplet'
        | 'stethoscope'
        | 'eye'
        | 'hospital'
        | 'graduation-cap'
        | 'award'
        | 'book-open'
        | 'laptop'
        | 'scissors'
        | 'trees'
        | 'sparkles'
        | 'package-check'
        | 'heart'
        | 'hand-coins'
        | 'waves'
        | 'sprout'
        | 'mountain'
        | 'house'
        | 'heart-handshake'
      )
    | null;
  /**
   * Leave empty to use the title.
   */
  menuLabel?: string | null;
  /**
   * Up to 4 photos that blend in behind the section while a visitor points at this programme’s tile. Order sets the place: 1 top left, 2 bottom, 3 right, 4 left.
   */
  hoverPhotos?:
    | {
        /**
         * Choose from the Media library, or upload a new file. This wins over a path.
         */
        media?: (number | null) | Media;
        /**
         * Only if you are not choosing an upload: a site path such as /images/photo.jpg, or an https:// link.
         */
        src?: string | null;
        alt?: string | null;
        id?: string | null;
      }[]
    | null;
  /**
   * Optional: shows one area of a hover photo at full strength, e.g. the people at its centre. Positions are percentages of that photo’s area.
   */
  hoverFocus?: {
    photo?: number | null;
    x?: number | null;
    y?: number | null;
    width?: number | null;
    height?: number | null;
  };
  /**
   * Faint photo behind this programme’s card on the Core Values page.
   */
  cardPhoto?: {
    /**
     * Choose from the Media library, or upload a new file. This wins over a path.
     */
    media?: (number | null) | Media;
    /**
     * Only if you are not choosing an upload: a site path such as /images/photo.jpg, or an https:// link.
     */
    src?: string | null;
    alt?: string | null;
  };
  images?:
    | {
        /**
         * Choose from the Media library, or upload a new file. This wins over a path.
         */
        media?: (number | null) | Media;
        /**
         * Only if you are not choosing an upload: a site path such as /images/photo.jpg, or an https:// link.
         */
        src?: string | null;
        /**
         * What the picture shows, for visitors who cannot see it.
         */
        alt?: string | null;
        caption?: string | null;
        /**
         * Filled in automatically for uploads.
         */
        width?: number | null;
        /**
         * Filled in automatically for uploads.
         */
        height?: number | null;
        /**
         * Keeps this spot in view when cropped, e.g. 50% 30%.
         */
        focal?: string | null;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * Every photo, film, sound and 3D model uploaded for the website. Upload here, then choose the file wherever an image is asked for.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  /**
   * For example Pavilion / Heal or Projects / Amrit.
   */
  folder?: string | null;
  tags?:
    | {
        tag: string;
        id?: string | null;
      }[]
    | null;
  illustrative?: boolean | null;
  license?: string | null;
  sourceURL?: string | null;
  duration?: number | null;
  /**
   * What the picture shows, for readers who cannot see it. Describe the scene, not the file.
   */
  alt: string;
  /**
   * Shown under the image where the design allows it.
   */
  caption?: string | null;
  /**
   * Photographer or source, where one should be named.
   */
  credit?: string | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
  sizes?: {
    thumb?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    card?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    full?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
  };
}
/**
 * Annual observances and ongoing programmes shown in the events journal.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "events".
 */
export interface Event {
  id: number;
  /**
   * How the website finds this item. Set once; only an administrator can change it.
   */
  key: string;
  /**
   * Lower numbers come first.
   */
  order?: number | null;
  title: string;
  kind: 'annual' | 'ongoing';
  month?: number | null;
  day?: number | null;
  pillarId: 'heal' | 'enrich' | 'empower' | 'projects';
  tag?: string | null;
  blurb?: string | null;
  location?: string | null;
  time?: string | null;
  /**
   * A page on this site such as /projects, or an https:// link.
   */
  href?: string | null;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * Organisations the foundation works with: what they did together, and how their logo appears.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "partners".
 */
export interface Partner {
  id: number;
  /**
   * How the website finds this item. Set once; only an administrator can change it.
   */
  key: string;
  /**
   * Lower numbers come first.
   */
  order?: number | null;
  name: string;
  contribution: string;
  note?: string | null;
  /**
   * Choose from the Media library, or upload a new file. This wins over a path.
   */
  logoMedia?: (number | null) | Media;
  /**
   * Only if you are not choosing an upload: a site path such as /images/photo.jpg, or an https:// link.
   */
  logo?: string | null;
  /**
   * For the partner wall, e.g. “Indian Red Cross”.
   */
  short?: string | null;
  /**
   * Shown when there is no logo.
   */
  initials?: string | null;
  /**
   * Hex colour such as #24785b. Pick it with the swatch.
   */
  color?: string | null;
  /**
   * Only if you are not choosing an upload: a site path such as /images/photo.jpg, or an https:// link.
   */
  href?: string | null;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * Verified honours only. Leave the year empty when the source does not give one.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "awards".
 */
export interface Award {
  id: number;
  /**
   * How the website finds this item. Set once; only an administrator can change it.
   */
  key: string;
  /**
   * Lower numbers come first.
   */
  order?: number | null;
  title: string;
  awardedBy: string;
  year?: string | null;
  note?: string | null;
  featured?: boolean | null;
  photos?:
    | {
        /**
         * Choose from the Media library, or upload a new file. This wins over a path.
         */
        media?: (number | null) | Media;
        /**
         * Only if you are not choosing an upload: a site path such as /images/photo.jpg, or an https:// link.
         */
        src?: string | null;
        /**
         * What the picture shows, for visitors who cannot see it.
         */
        alt?: string | null;
        caption?: string | null;
        /**
         * Filled in automatically for uploads.
         */
        width?: number | null;
        /**
         * Filled in automatically for uploads.
         */
        height?: number | null;
        /**
         * Keeps this spot in view when cropped, e.g. 50% 30%.
         */
        focal?: string | null;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * Every heading, sentence, button and label on the site. Filter by Page, or search for the words you see on the website.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "content-slots".
 */
export interface ContentSlot {
  id: number;
  /**
   * How the website finds this item. Set once; only an administrator can change it.
   */
  key: string;
  /**
   * Lower numbers come first.
   */
  order?: number | null;
  /**
   * Shown on the website exactly as written. Links: a page such as /projects or an https:// address.
   */
  value: string;
  /**
   * Filter the list by this to find a page’s text.
   */
  page?:
    | ('home' | 'core-values' | 'projects' | 'who-we-are' | 'guiding-force' | 'contribute' | 'everywhere' | 'other')
    | null;
  section?: string | null;
  label: string;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * Logos, portraits and artwork built into the page design. Programme, partner and gallery photos are edited on their own records.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "asset-slots".
 */
export interface AssetSlot {
  id: number;
  /**
   * How the website finds this item. Set once; only an administrator can change it.
   */
  key: string;
  /**
   * Lower numbers come first.
   */
  order?: number | null;
  /**
   * Choose from the Media library, or upload a new file. This wins over a path.
   */
  media?: (number | null) | Media;
  /**
   * Only if you are not choosing an upload: a site path such as /images/photo.jpg, or an https:// link.
   */
  source?: string | null;
  kind?: ('image' | 'video' | 'audio' | 'other') | null;
  /**
   * Filter the list by this to find a page’s text.
   */
  page?:
    | ('home' | 'core-values' | 'projects' | 'who-we-are' | 'guiding-force' | 'contribute' | 'everywhere' | 'other')
    | null;
  section?: string | null;
  label: string;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * Photos and films for each gallery. Pillar photos are five per pillar, in order: they fill the home page tiles, the photo emblem and the Core Values collage.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "gallery-items".
 */
export interface GalleryItem {
  id: number;
  /**
   * How the website finds this item. Set once; only an administrator can change it.
   */
  key: string;
  /**
   * Lower numbers come first.
   */
  order?: number | null;
  group:
    | 'pavilion:heal'
    | 'pavilion:enrich'
    | 'pavilion:empower'
    | 'pavilion:projects'
    | 'media:project-amrit'
    | 'media:oneness-vann'
    | 'media:watershed'
    | 'media:adopted-villages'
    | 'media:who-we-are'
    | 'media:guiding-force';
  kind?: ('photo' | 'film') | null;
  /**
   * Choose from the Media library, or upload a new file. This wins over a path.
   */
  media?: (number | null) | Media;
  /**
   * Only if you are not choosing an upload: a site path such as /images/photo.jpg, or an https:// link.
   */
  src?: string | null;
  /**
   * What the picture shows, for visitors who cannot see it.
   */
  alt?: string | null;
  caption?: string | null;
  /**
   * Filled in automatically for uploads.
   */
  width?: number | null;
  /**
   * Filled in automatically for uploads.
   */
  height?: number | null;
  /**
   * Keeps this spot in view when cropped, e.g. 50% 30%.
   */
  focal?: string | null;
  /**
   * Still shown before a film plays.
   */
  posterMedia?: (number | null) | Media;
  /**
   * Only if you are not choosing an upload: a site path such as /images/photo.jpg, or an https:// link.
   */
  poster?: string | null;
  /**
   * Only if you are not choosing an upload: a site path such as /images/photo.jpg, or an https:// link.
   */
  source?: string | null;
  wide?: boolean | null;
  illustrative?: boolean | null;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * The title and description search engines and link previews show for each page. Extra pages at /pages/<address> are built from sections.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages".
 */
export interface Page {
  id: number;
  /**
   * How the website finds this item. Set once; only an administrator can change it.
   */
  key: string;
  /**
   * Lower numbers come first.
   */
  order?: number | null;
  title: string;
  /**
   * core-values for /core-values; empty for the home page.
   */
  slug?: string | null;
  /**
   * One or two sentences shown in search results.
   */
  description?: string | null;
  sections?:
    | (
        | {
            key: string;
            heading?: string | null;
            body?: string | null;
            enabled?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'text';
          }
        | {
            key: string;
            /**
             * Choose from the Media library, or upload a new file. This wins over a path.
             */
            media?: (number | null) | Media;
            /**
             * Only if you are not choosing an upload: a site path such as /images/photo.jpg, or an https:// link.
             */
            src?: string | null;
            /**
             * What the picture shows, for visitors who cannot see it.
             */
            alt?: string | null;
            caption?: string | null;
            /**
             * Filled in automatically for uploads.
             */
            width?: number | null;
            /**
             * Filled in automatically for uploads.
             */
            height?: number | null;
            /**
             * Keeps this spot in view when cropped, e.g. 50% 30%.
             */
            focal?: string | null;
            /**
             * Only if you are not choosing an upload: a site path such as /images/photo.jpg, or an https:// link.
             */
            video?: string | null;
            heading?: string | null;
            body?: string | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'media';
          }
        | {
            key: string;
            heading?: string | null;
            cards?:
              | {
                  title?: string | null;
                  body?: string | null;
                  /**
                   * Only if you are not choosing an upload: a site path such as /images/photo.jpg, or an https:// link.
                   */
                  href?: string | null;
                  /**
                   * Choose from the Media library, or upload a new file. This wins over a path.
                   */
                  media?: (number | null) | Media;
                  /**
                   * Only if you are not choosing an upload: a site path such as /images/photo.jpg, or an https:// link.
                   */
                  src?: string | null;
                  /**
                   * What the picture shows, for visitors who cannot see it.
                   */
                  alt?: string | null;
                  caption?: string | null;
                  /**
                   * Filled in automatically for uploads.
                   */
                  width?: number | null;
                  /**
                   * Filled in automatically for uploads.
                   */
                  height?: number | null;
                  /**
                   * Keeps this spot in view when cropped, e.g. 50% 30%.
                   */
                  focal?: string | null;
                  id?: string | null;
                }[]
              | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'cards';
          }
        | {
            key: string;
            component?: ('events' | 'awards') | null;
            enabled?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'custom';
          }
      )[]
    | null;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * Show or hide whole sections. For home page sections, Display order sets their position from the top.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "component-settings".
 */
export interface ComponentSetting {
  id: number;
  /**
   * How the website finds this item. Set once; only an administrator can change it.
   */
  key: string;
  /**
   * Lower numbers come first.
   */
  order?: number | null;
  label?: string | null;
  enabled?: boolean | null;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * The published figures behind every number on the site. Programme and pillar forms update these automatically; edit here for corrections and sources.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "live-stats".
 */
export interface LiveStat {
  id: number;
  /**
   * How the website finds this item. Set once; only an administrator can change it.
   */
  key: string;
  /**
   * Lower numbers come first.
   */
  order?: number | null;
  label: string;
  /**
   * Exactly as reported.
   */
  value: string;
  period?: string | null;
  asOf?: string | null;
  source?: string | null;
  /**
   * Report or page the figure comes from.
   */
  sourceURL?: string | null;
  verifiedAt?: string | null;
  /**
   * Not shown on the website.
   */
  notes?: string | null;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * Every published change to a live figure: what it was, what it became, and who published it.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "stat-audit".
 */
export interface StatAudit {
  id: number;
  key: string;
  label?: string | null;
  value?: string | null;
  previousValue?: string | null;
  period?: string | null;
  source?: string | null;
  operation?: string | null;
  actor?: (number | null) | User;
  updatedAt: string;
  createdAt: string;
}
/**
 * People who can sign in to the studio, and what each may do.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  name: string;
  /**
   * Only an admin can change this.
   */
  role: 'contributor' | 'editor' | 'admin';
  updatedAt: string;
  createdAt: string;
  enableAPIKey?: boolean | null;
  apiKey?: string | null;
  apiKeyIndex?: string | null;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'pillars';
        value: number | Pillar;
      } | null)
    | ({
        relationTo: 'activities';
        value: number | Activity;
      } | null)
    | ({
        relationTo: 'events';
        value: number | Event;
      } | null)
    | ({
        relationTo: 'partners';
        value: number | Partner;
      } | null)
    | ({
        relationTo: 'awards';
        value: number | Award;
      } | null)
    | ({
        relationTo: 'content-slots';
        value: number | ContentSlot;
      } | null)
    | ({
        relationTo: 'asset-slots';
        value: number | AssetSlot;
      } | null)
    | ({
        relationTo: 'gallery-items';
        value: number | GalleryItem;
      } | null)
    | ({
        relationTo: 'pages';
        value: number | Page;
      } | null)
    | ({
        relationTo: 'component-settings';
        value: number | ComponentSetting;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'live-stats';
        value: number | LiveStat;
      } | null)
    | ({
        relationTo: 'stat-audit';
        value: number | StatAudit;
      } | null)
    | ({
        relationTo: 'users';
        value: number | User;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pillars_select".
 */
export interface PillarsSelect<T extends boolean = true> {
  key?: T;
  order?: T;
  label?: T;
  headline?: T;
  body?: T;
  shortTagline?: T;
  subText?: T;
  emblemCaption?: T;
  cardImageAlt?: T;
  stats?:
    | T
    | {
        label?: T;
        value?: T;
        id?: T;
      };
  keyHighlights?:
    | T
    | {
        text?: T;
        id?: T;
      };
  accentA?: T;
  accentB?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "activities_select".
 */
export interface ActivitiesSelect<T extends boolean = true> {
  key?: T;
  order?: T;
  pillarId?: T;
  title?: T;
  period?: T;
  blurb?: T;
  headline?:
    | T
    | {
        label?: T;
        value?: T;
        id?: T;
      };
  dataPoints?:
    | T
    | {
        label?: T;
        value?: T;
        id?: T;
      };
  icon?: T;
  menuLabel?: T;
  hoverPhotos?:
    | T
    | {
        media?: T;
        src?: T;
        alt?: T;
        id?: T;
      };
  hoverFocus?:
    | T
    | {
        photo?: T;
        x?: T;
        y?: T;
        width?: T;
        height?: T;
      };
  cardPhoto?:
    | T
    | {
        media?: T;
        src?: T;
        alt?: T;
      };
  images?:
    | T
    | {
        media?: T;
        src?: T;
        alt?: T;
        caption?: T;
        width?: T;
        height?: T;
        focal?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "events_select".
 */
export interface EventsSelect<T extends boolean = true> {
  key?: T;
  order?: T;
  title?: T;
  kind?: T;
  month?: T;
  day?: T;
  pillarId?: T;
  tag?: T;
  blurb?: T;
  location?: T;
  time?: T;
  href?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "partners_select".
 */
export interface PartnersSelect<T extends boolean = true> {
  key?: T;
  order?: T;
  name?: T;
  contribution?: T;
  note?: T;
  logoMedia?: T;
  logo?: T;
  short?: T;
  initials?: T;
  color?: T;
  href?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "awards_select".
 */
export interface AwardsSelect<T extends boolean = true> {
  key?: T;
  order?: T;
  title?: T;
  awardedBy?: T;
  year?: T;
  note?: T;
  featured?: T;
  photos?:
    | T
    | {
        media?: T;
        src?: T;
        alt?: T;
        caption?: T;
        width?: T;
        height?: T;
        focal?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "content-slots_select".
 */
export interface ContentSlotsSelect<T extends boolean = true> {
  key?: T;
  order?: T;
  value?: T;
  page?: T;
  section?: T;
  label?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "asset-slots_select".
 */
export interface AssetSlotsSelect<T extends boolean = true> {
  key?: T;
  order?: T;
  media?: T;
  source?: T;
  kind?: T;
  page?: T;
  section?: T;
  label?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "gallery-items_select".
 */
export interface GalleryItemsSelect<T extends boolean = true> {
  key?: T;
  order?: T;
  group?: T;
  kind?: T;
  media?: T;
  src?: T;
  alt?: T;
  caption?: T;
  width?: T;
  height?: T;
  focal?: T;
  posterMedia?: T;
  poster?: T;
  source?: T;
  wide?: T;
  illustrative?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages_select".
 */
export interface PagesSelect<T extends boolean = true> {
  key?: T;
  order?: T;
  title?: T;
  slug?: T;
  description?: T;
  sections?:
    | T
    | {
        text?:
          | T
          | {
              key?: T;
              heading?: T;
              body?: T;
              enabled?: T;
              id?: T;
              blockName?: T;
            };
        media?:
          | T
          | {
              key?: T;
              media?: T;
              src?: T;
              alt?: T;
              caption?: T;
              width?: T;
              height?: T;
              focal?: T;
              video?: T;
              heading?: T;
              body?: T;
              id?: T;
              blockName?: T;
            };
        cards?:
          | T
          | {
              key?: T;
              heading?: T;
              cards?:
                | T
                | {
                    title?: T;
                    body?: T;
                    href?: T;
                    media?: T;
                    src?: T;
                    alt?: T;
                    caption?: T;
                    width?: T;
                    height?: T;
                    focal?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        custom?:
          | T
          | {
              key?: T;
              component?: T;
              enabled?: T;
              id?: T;
              blockName?: T;
            };
      };
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "component-settings_select".
 */
export interface ComponentSettingsSelect<T extends boolean = true> {
  key?: T;
  order?: T;
  label?: T;
  enabled?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  folder?: T;
  tags?:
    | T
    | {
        tag?: T;
        id?: T;
      };
  illustrative?: T;
  license?: T;
  sourceURL?: T;
  duration?: T;
  alt?: T;
  caption?: T;
  credit?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
  sizes?:
    | T
    | {
        thumb?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        card?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        full?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "live-stats_select".
 */
export interface LiveStatsSelect<T extends boolean = true> {
  key?: T;
  order?: T;
  label?: T;
  value?: T;
  period?: T;
  asOf?: T;
  source?: T;
  sourceURL?: T;
  verifiedAt?: T;
  notes?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "stat-audit_select".
 */
export interface StatAuditSelect<T extends boolean = true> {
  key?: T;
  label?: T;
  value?: T;
  previousValue?: T;
  period?: T;
  source?: T;
  operation?: T;
  actor?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  name?: T;
  role?: T;
  updatedAt?: T;
  createdAt?: T;
  enableAPIKey?: T;
  apiKey?: T;
  apiKeyIndex?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * Name, logo, contact details, menu, footer, social links and search-engine text.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-settings".
 */
export interface SiteSetting {
  id: number;
  branding?: {
    name?: string | null;
    tagline?: string | null;
    /**
     * Shown in the header and footer.
     */
    logoMedia?: (number | null) | Media;
    /**
     * Only if you are not choosing an upload: a site path such as /images/photo.jpg, or an https:// link.
     */
    logo?: string | null;
  };
  contact?: {
    email?: string | null;
    telephone?: string | null;
    address?: string | null;
  };
  navigation?:
    | {
        label: string;
        /**
         * A page on this site such as /projects or /who-we-are#partners, or an https:// address.
         */
        href?: string | null;
        /**
         * “Programmes by pillar” lists every programme, grouped under Heal, Enrich and Empower.
         */
        menu?: ('none' | 'links' | 'programmes') | null;
        external?: boolean | null;
        links?:
          | {
              label: string;
              /**
               * A page on this site such as /projects or /who-we-are#partners, or an https:// address.
               */
              href?: string | null;
              external?: boolean | null;
              id?: string | null;
            }[]
          | null;
        id?: string | null;
      }[]
    | null;
  footerColumns?:
    | {
        title: string;
        links?:
          | {
              label: string;
              /**
               * A page on this site such as /projects or /who-we-are#partners, or an https:// address.
               */
              href?: string | null;
              id?: string | null;
            }[]
          | null;
        id?: string | null;
      }[]
    | null;
  /**
   * Icons down the left edge of the site, in this order. Leave a link empty to hide that icon.
   */
  social?:
    | {
        platform: 'instagram' | 'youtube' | 'spotify' | 'facebook' | 'x' | 'linkedin' | 'whatsapp';
        /**
         * The full https:// address of the profile or channel.
         */
        url?: string | null;
        id?: string | null;
      }[]
    | null;
  seo?: {
    title?: string | null;
    description?: string | null;
    /**
     * Shown when the site is shared on social media.
     */
    imageMedia?: (number | null) | Media;
    /**
     * Only if you are not choosing an upload: a site path such as /images/photo.jpg, or an https:// link.
     */
    image?: string | null;
  };
  _status?: ('draft' | 'published') | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * The 3D models shown in the pillar cards and on the Projects page. Upload a .glb file to the Media library and choose it here.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pavilion-settings".
 */
export interface PavilionSetting {
  id: number;
  settings?: {
    models?: {
      /**
       * A .glb upload. This wins over a path.
       */
      healMedia?: (number | null) | Media;
      /**
       * For example /models/heal.glb.
       */
      heal?: string | null;
      /**
       * A .glb upload. This wins over a path.
       */
      enrichMedia?: (number | null) | Media;
      /**
       * For example /models/heal.glb.
       */
      enrich?: string | null;
      /**
       * A .glb upload. This wins over a path.
       */
      empowerMedia?: (number | null) | Media;
      /**
       * For example /models/heal.glb.
       */
      empower?: string | null;
      /**
       * A .glb upload. This wins over a path.
       */
      projectsMedia?: (number | null) | Media;
      /**
       * For example /models/heal.glb.
       */
      projects?: string | null;
      /**
       * A .glb upload. This wins over a path.
       */
      amritMedia?: (number | null) | Media;
      /**
       * For example /models/heal.glb.
       */
      amrit?: string | null;
      /**
       * A .glb upload. This wins over a path.
       */
      onenessMedia?: (number | null) | Media;
      /**
       * For example /models/heal.glb.
       */
      oneness?: string | null;
    };
  };
  _status?: ('draft' | 'published') | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-settings_select".
 */
export interface SiteSettingsSelect<T extends boolean = true> {
  branding?:
    | T
    | {
        name?: T;
        tagline?: T;
        logoMedia?: T;
        logo?: T;
      };
  contact?:
    | T
    | {
        email?: T;
        telephone?: T;
        address?: T;
      };
  navigation?:
    | T
    | {
        label?: T;
        href?: T;
        menu?: T;
        external?: T;
        links?:
          | T
          | {
              label?: T;
              href?: T;
              external?: T;
              id?: T;
            };
        id?: T;
      };
  footerColumns?:
    | T
    | {
        title?: T;
        links?:
          | T
          | {
              label?: T;
              href?: T;
              id?: T;
            };
        id?: T;
      };
  social?:
    | T
    | {
        platform?: T;
        url?: T;
        id?: T;
      };
  seo?:
    | T
    | {
        title?: T;
        description?: T;
        imageMedia?: T;
        image?: T;
      };
  _status?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pavilion-settings_select".
 */
export interface PavilionSettingsSelect<T extends boolean = true> {
  settings?:
    | T
    | {
        models?:
          | T
          | {
              healMedia?: T;
              heal?: T;
              enrichMedia?: T;
              enrich?: T;
              empowerMedia?: T;
              empower?: T;
              projectsMedia?: T;
              projects?: T;
              amritMedia?: T;
              amrit?: T;
              onenessMedia?: T;
              oneness?: T;
            };
      };
  _status?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}