/* Generated by scripts/build-mosaic-wall.ts — do not edit; run npm run images:wall. */
export const MOSAIC_WALL = {
  src: '/images/mosaic-wall.webp',
  cols: 12,
  rows: 4,
  /** Each tile's pillar, in the sprite's order (left to right, top to bottom). */
  tiles: ["heal","heal","heal","heal","heal","heal","heal","heal","heal","heal","heal","heal","enrich","enrich","enrich","enrich","enrich","enrich","enrich","enrich","enrich","enrich","enrich","enrich","empower","empower","empower","empower","empower","empower","empower","empower","empower","empower","empower","empower","projects","projects","projects","projects","projects","projects","projects","projects","projects"] as ('heal' | 'enrich' | 'empower' | 'projects')[],
};
