/**
 * Builds the photo wall behind the home page's "Four paths" overture.
 *
 *   npm run images:wall     writes public/images/mosaic-wall.webp and src/components/mosaicWallTiles.ts
 *
 * The wall is the foundation's own programme photographs, a dozen from each
 * pillar, cut into small greyscale tiles on ONE sprite: one request of a few
 * hundred kilobytes instead of fifty full-size photographs. The page tints
 * the tiles (CSS background-blend-mode), so a pillar's tiles can glow in its
 * colour while the rest stay in the section's green. Run it again when the
 * programme photographs change. Sharp is the backend's (the site has none).
 */
import { writeFileSync } from 'node:fs';
import { createRequire } from 'node:module';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';
import { DEFAULT_ACTIVITIES } from '../src/data/activities';

const root = join(dirname(fileURLToPath(import.meta.url)), '..');
const sharp = createRequire(import.meta.url)(join(root, 'backend/node_modules/sharp'));

const PILLARS = ['heal', 'enrich', 'empower', 'projects'] as const;
const PER_PILLAR = 12;
const TILE = { w: 200, h: 150 };
const SPRITE_COLS = 12;
/* the Health City has no programme photographs of its own yet; its building stands in */
const EXTRA: Record<string, string[]> = { projects: ['/images/projects/health-city.webp'] };

const picks: { pillar: string; src: string }[] = [];
for (const pillar of PILLARS) {
  const seen = new Set<string>();
  const srcs = [...DEFAULT_ACTIVITIES.filter(a => a.pillarId === pillar).flatMap(a => (a.images ?? []).map(i => i.src)), ...(EXTRA[pillar] ?? [])]
    .filter(src => src.startsWith('/') && !seen.has(src) && seen.add(src));
  /* take evenly across the pillar's programmes rather than the first one's twelve */
  const step = Math.max(1, srcs.length / PER_PILLAR);
  for (let i = 0; i < Math.min(PER_PILLAR, srcs.length); i++) picks.push({ pillar, src: srcs[Math.floor(i * step)] });
}

const rows = Math.ceil(picks.length / SPRITE_COLS);
const tiles = await Promise.all(picks.map(({ src }) =>
  sharp(join(root, 'public', src)).resize(TILE.w, TILE.h, { fit: 'cover', position: 'attention' }).grayscale().normalise().toBuffer()));
await sharp({ create: { width: SPRITE_COLS * TILE.w, height: rows * TILE.h, channels: 3, background: '#5a6e66' } })
  .composite(tiles.map((input, i) => ({ input, left: (i % SPRITE_COLS) * TILE.w, top: Math.floor(i / SPRITE_COLS) * TILE.h })))
  .webp({ quality: 60 })
  .toFile(join(root, 'public/images/mosaic-wall.webp'));

writeFileSync(join(root, 'src/components/mosaicWallTiles.ts'), `/* Generated by scripts/build-mosaic-wall.ts — do not edit; run npm run images:wall. */
export const MOSAIC_WALL = {
  src: '/images/mosaic-wall.webp',
  cols: ${SPRITE_COLS},
  rows: ${rows},
  /** Each tile's pillar, in the sprite's order (left to right, top to bottom). */
  tiles: ${JSON.stringify(picks.map(p => p.pillar))} as ('heal' | 'enrich' | 'empower' | 'projects')[],
};
`);
console.log(`mosaic wall: ${picks.length} tiles (${PILLARS.map(p => `${p} ${picks.filter(t => t.pillar === p).length}`).join(', ')}), sprite ${SPRITE_COLS}×${rows}`);
